// COLOR SCHEMES
export const BACKGROUND_COLOR = '#FFFFF';
export const PRIMARY_COLOR = '#474B53';
export const SECONDARY_COLOR = '#F2F2F2';
export const PRIMARY_ACCENT_COLOR = '#E35268';
export const SECONDARY_ACCENT_COLOR = '#56DDBE';

// TEXT SCHEMES